#!/usr/bin/env bun

import { 
  AccountSystem, 
  AccountMerkleTree, 
  TransferSystem,
  toField,
  type Account
} from './account-system';
import { writeFileSync } from 'node:fs';

// Generate comprehensive test data for the account-based circuit
function generateAccountTestData(): {
  alice: {
    secret: string;
    old_account: Account;
    new_account: Account;
  };
  bob: {
    old_account: Account;
    new_account: Account;
  };
  transfer: {
    amount: string;
    nullifier: string;
    merkle_proof: {
      root: string;
      path: string[];
      indices: string[];
    };
  };
  circuit_inputs: {
    public_inputs: object;
    private_inputs: object;
  };
} {
  console.log('🏗️  Generating account-based circuit test data...\n');

  // Create Alice and Bob with realistic initial states
  const aliceSecret = toField('0xALICE123456789');
  const bobSecret = toField('0xB0B987654321');
  
  const aliceOldAccount = AccountSystem.createAccount(aliceSecret, 1000, 5, 1);
  const bobOldAccount = AccountSystem.createAccount(bobSecret, 200, 3, 1);
  
  console.log('👤 Alice Initial State:');
  console.log(`   Secret: ${aliceSecret}`);
  console.log(`   Public Key: ${aliceOldAccount.pubkey}`);
  console.log(`   Balance: ${aliceOldAccount.balance} (1000 tokens)`);
  console.log(`   Nonce: ${aliceOldAccount.nonce}`);
  console.log(`   Asset ID: ${aliceOldAccount.asset_id}`);
  
  console.log('\n👤 Bob Initial State:');
  console.log(`   Public Key: ${bobOldAccount.pubkey}`);
  console.log(`   Balance: ${bobOldAccount.balance} (200 tokens)`);
  console.log(`   Nonce: ${bobOldAccount.nonce}`);
  console.log(`   Asset ID: ${bobOldAccount.asset_id}`);

  // Create Merkle tree with Alice's account
  const tree = new AccountMerkleTree([aliceOldAccount]);
  
  // Alice sends 300 tokens to Bob
  const transferAmount = 300;
  console.log(`\n💸 Transfer: Alice → Bob (${transferAmount} tokens)`);
  
  const transfer = TransferSystem.createTransfer(
    aliceSecret,
    aliceOldAccount,
    bobOldAccount.pubkey,
    bobOldAccount,
    transferAmount,
    tree
  );
  
  // Generate circuit inputs
  const circuitInputs = TransferSystem.generateCircuitInputs(transfer);
  
  console.log('\n✅ Final States:');
  console.log(`   Alice New Balance: ${transfer.sender_new.balance} (700 tokens)`);
  console.log(`   Alice New Nonce: ${transfer.sender_new.nonce}`);
  console.log(`   Bob New Balance: ${transfer.recipient_new.balance} (500 tokens)`);
  console.log(`   Bob New Nonce: ${transfer.recipient_new.nonce}`);
  
  console.log('\n🔒 Security Components:');
  console.log(`   Alice Nullifier: ${circuitInputs.public_inputs.sender_nullifier}`);
  console.log(`   Alice New Commitment: ${circuitInputs.public_inputs.sender_new_commitment}`);
  console.log(`   Bob New Commitment: ${circuitInputs.public_inputs.recipient_new_commitment}`);
  console.log(`   Merkle Root: ${circuitInputs.public_inputs.merkle_root}`);

  return {
    alice: {
      secret: aliceSecret,
      old_account: aliceOldAccount,
      new_account: transfer.sender_new,
    },
    bob: {
      old_account: bobOldAccount,
      new_account: transfer.recipient_new,
    },
    transfer: {
      amount: transfer.transfer_amount,
      nullifier: circuitInputs.public_inputs.sender_nullifier,
      merkle_proof: {
        root: transfer.merkle_proof.root,
        path: transfer.merkle_proof.path,
        indices: transfer.merkle_proof.indices,
      },
    },
    circuit_inputs: {
      public_inputs: circuitInputs.public_inputs,
      private_inputs: circuitInputs.private_inputs,
    },
  };
}

// Generate Noir-compatible TOML format
function generateNoirInputs(data: ReturnType<typeof generateAccountTestData>): string {
  const { circuit_inputs } = data;
  const { public_inputs, private_inputs } = circuit_inputs;
  
  // Format arrays for TOML
  const formatArray = (arr: string[]) => {
    return '[\n' + arr.map(item => `    "${item}"`).join(',\n') + '\n]';
  };

  return `# Account-based private transfer circuit inputs
# Generated by generate-account-proof.ts

# ===== PUBLIC INPUTS =====
merkle_root = "${public_inputs.merkle_root}"
sender_nullifier = "${public_inputs.sender_nullifier}" 
sender_new_commitment = "${public_inputs.sender_new_commitment}"
recipient_new_commitment = "${public_inputs.recipient_new_commitment}"
asset_id = "${public_inputs.asset_id}"

# ===== PRIVATE INPUTS =====

# Sender's current account
[sender_account]
pubkey = "${private_inputs.sender_account.pubkey}"
balance = "${private_inputs.sender_account.balance}"
nonce = "${private_inputs.sender_account.nonce}"
asset_id = "${private_inputs.sender_account.asset_id}"

# Sender's new account after transfer
[sender_new_account]
pubkey = "${private_inputs.sender_new_account.pubkey}"
balance = "${private_inputs.sender_new_account.balance}"
nonce = "${private_inputs.sender_new_account.nonce}"
asset_id = "${private_inputs.sender_new_account.asset_id}"

# Transfer details
sender_secret_key = "${private_inputs.sender_secret_key}"
transfer_amount = "${private_inputs.transfer_amount}"
recipient_pubkey = "${private_inputs.recipient_pubkey}"
recipient_old_balance = "${private_inputs.recipient_old_balance}"
recipient_old_nonce = "${private_inputs.recipient_old_nonce}"

# Merkle proof (20 levels)
sender_merkle_path = ${formatArray(private_inputs.sender_merkle_path)}

sender_merkle_indices = ${formatArray(private_inputs.sender_merkle_indices)}

# ===== SECURITY ANALYSIS =====
# 
# This transfer satisfies all security constraints:
# 1. ✅ Alice owns the account she's spending (pubkey matches secret)
# 2. ✅ Alice's account exists in Merkle tree (proof verifies)
# 3. ✅ Alice has sufficient balance (1000 >= 300)
# 4. ✅ Conservation of value (1000 = 700 + 300)
# 5. ✅ Nullifier prevents double-spending
# 6. ✅ Bob generates his own commitment (interactive protocol)
# 7. ✅ No negative balances or overflow
# 8. ✅ Asset consistency throughout transfer
#
# Key Security Feature: Alice CANNOT rug Bob because:
# - Bob creates his own commitment with his own secret nonce
# - Alice only knows Bob's old state and transfer amount
# - Alice cannot generate Bob's new commitment without Bob's secret
# - When Bob later spends, he proves he knows the values in his commitment
`;
}

// Main execution
function main() {
  try {
    console.log('🚀 Starting account-based circuit proof generation...\n');
    
    const testData = generateAccountTestData();
    
    // Save JSON data
    const jsonData = JSON.stringify(testData, null, 2);
    writeFileSync('./account-test-data.json', jsonData);
    console.log('\n📄 Saved JSON data to account-test-data.json');
    
    // Save Noir inputs
    const noirInputs = generateNoirInputs(testData);
    writeFileSync('./account-circuit-inputs.toml', noirInputs);
    console.log('📄 Saved Noir inputs to account-circuit-inputs.toml');
    
    console.log('\n🎯 Usage:');
    console.log('   1. Copy account-circuit-inputs.toml to ../Prover.toml');
    console.log('   2. Run: nargo compile');
    console.log('   3. Run: nargo execute');
    console.log('   4. Run: bb prove -b ./target/account_system.json -w ./target/account_system.gz -o ./target/proof');
    console.log('   5. Run: bb verify -b ./target/account_system.json -v ./target/vkey -p ./target/proof');
    
    console.log('\n✨ Circuit ready for testing!');
    
  } catch (error) {
    console.error('❌ Error generating test data:', error);
    process.exit(1);
  }
}

// Performance test
function performanceTest() {
  console.log('\n⚡ Running performance tests...');
  
  const iterations = 100;
  const startTime = Date.now();
  
  for (let i = 0; i < iterations; i++) {
    const aliceSecret = toField(`0x${i.toString(16).padStart(8, '0')}`);
    const bobSecret = toField(`0x${(i + 1000).toString(16).padStart(8, '0')}`);
    
    const aliceAccount = AccountSystem.createAccount(aliceSecret, 1000 + i, i, 1);
    const bobAccount = AccountSystem.createAccount(bobSecret, 200 + i, i, 1);
    
    const tree = new AccountMerkleTree([aliceAccount]);
    const transfer = TransferSystem.createTransfer(
      aliceSecret, aliceAccount, bobAccount.pubkey, bobAccount, 100, tree
    );
    
    TransferSystem.generateCircuitInputs(transfer);
  }
  
  const endTime = Date.now();
  const avgTime = (endTime - startTime) / iterations;
  
  console.log(`   ✅ Generated ${iterations} transfers in ${endTime - startTime}ms`);
  console.log(`   ✅ Average time per transfer: ${avgTime.toFixed(2)}ms`);
  console.log(`   ✅ Throughput: ${(1000 / avgTime).toFixed(0)} transfers/second`);
}

// Run main function
if (import.meta.main) {
  main();
  performanceTest();
}

export { generateAccountTestData, generateNoirInputs };